/**
 * Definições e Recomendações dos Provedores de API Integrados ao BR Quest
 */

import type { ApiCallLog, ApiProviderSummary, WeeklyRecommendation } from './apiTrackerTypes';

export function buildProvidersSummary(
  logs: ApiCallLog[],
  quotaCounts: Record<string, number>,
  cachedSavings: Record<string, number>
): ApiProviderSummary[] {
  const getAvgLatency = (prov: string) => {
    const provLogs = logs.filter((l) => l.provider === prov && l.status === 'success');
    if (!provLogs.length) return 45;
    const total = provLogs.reduce((acc, l) => acc + l.durationMs, 0);
    return Math.round(total / provLogs.length);
  };

  const getLastTime = (prov: string) => {
    const l = logs.find((log) => log.provider === prov);
    return l ? l.timestamp : null;
  };

  const openMeteoToday = quotaCounts['open-meteo'] || 0;
  const openMeteoWeekly = Math.max(openMeteoToday, openMeteoToday * 7);

  return [
    {
      id: 'open-meteo',
      name: 'Open-Meteo (ECMWF & NOAA)',
      description: 'Previsões meteorológicas, ventos a 10m, pressão e temperatura horária para os 27 estados do Brasil.',
      planName: 'Non-Commercial Free Tier',
      quotaPerDay: '10.000 req/dia',
      quotaDailyLimit: 10000,
      quotaWeeklyLimit: 70000,
      quotaUsedToday: openMeteoToday,
      quotaUsedThisWeek: openMeteoToday,
      projectedWeeklyUsage: Math.max(openMeteoToday * 7, 28),
      usagePercentWeekly: Number(((openMeteoWeekly / 70000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('open-meteo'),
      lastCallTime: getLastTime('open-meteo'),
      cachedEntries: logs.filter((l) => l.provider === 'open-meteo' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['open-meteo'] || 0,
      recommendedTtl: '15 minutos (Lazy Loading sob demanda)',
      rateLimitPolicy: 'Máximo 1 chamada por estado a cada 15 min; apenas ao abrir a aba Clima',
    },
    {
      id: 'gbif-biodiversity',
      name: 'GBIF (Global Biodiversity Facility)',
      description: 'Rede global de dados abertos para taxonomia biológica, ocorrências de espécimes e registros científicos no Brasil.',
      planName: 'Open Science Public Access',
      quotaPerDay: 'Ilimitado (Fair Use ~20 req/s)',
      quotaDailyLimit: 50000,
      quotaWeeklyLimit: 350000,
      quotaUsedToday: quotaCounts['gbif-biodiversity'] || 0,
      quotaUsedThisWeek: quotaCounts['gbif-biodiversity'] || 0,
      projectedWeeklyUsage: (quotaCounts['gbif-biodiversity'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['gbif-biodiversity'] || 0) * 7) / 350000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('gbif-biodiversity'),
      lastCallTime: getLastTime('gbif-biodiversity'),
      cachedEntries: logs.filter((l) => l.provider === 'gbif-biodiversity' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['gbif-biodiversity'] || 0,
      recommendedTtl: '24 horas (localStorage)',
      rateLimitPolicy: '1 chamada por táxon ao inspecionar espécie; cache persistente de 24h',
    },
    {
      id: 'inaturalist',
      name: 'iNaturalist API v1 (Pesquisa Científica BR)',
      description: 'Fotografias e observações da fauna, flora e fungos brasileiros verificadas em grau de pesquisa científica (place_id=6878).',
      planName: 'Open Data & Research API',
      quotaPerDay: 'Ilimitado (Fair Use ~60 req/min)',
      quotaDailyLimit: 30000,
      quotaWeeklyLimit: 210000,
      quotaUsedToday: quotaCounts['inaturalist'] || 0,
      quotaUsedThisWeek: quotaCounts['inaturalist'] || 0,
      projectedWeeklyUsage: (quotaCounts['inaturalist'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['inaturalist'] || 0) * 7) / 210000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('inaturalist'),
      lastCallTime: getLastTime('inaturalist'),
      cachedEntries: logs.filter((l) => l.provider === 'inaturalist' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['inaturalist'] || 0,
      recommendedTtl: '14 dias (localStorage + cache em memória)',
      rateLimitPolicy: 'Fila concorrente (máx 2 simultâneas), throttle 250ms e cache negativo 24h',
    },
    {
      id: 'jbrj-reflora',
      name: 'Flora e Funga do Brasil (JBRJ & Reflora)',
      description: 'Acervo taxonômico oficial do Jardim Botânico do Rio de Janeiro e Herbário Virtual Reflora para espécies nativas e ameaçadas.',
      planName: 'Dados Abertos MCTI / JBRJ',
      quotaPerDay: 'Ilimitado (Catálogo Nacional)',
      quotaDailyLimit: 20000,
      quotaWeeklyLimit: 140000,
      quotaUsedToday: quotaCounts['jbrj-reflora'] || 0,
      quotaUsedThisWeek: quotaCounts['jbrj-reflora'] || 0,
      projectedWeeklyUsage: (quotaCounts['jbrj-reflora'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['jbrj-reflora'] || 0) * 7) / 140000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('jbrj-reflora'),
      lastCallTime: getLastTime('jbrj-reflora'),
      cachedEntries: logs.filter((l) => l.provider === 'jbrj-reflora' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['jbrj-reflora'] || 0,
      recommendedTtl: 'Permanente / 14 dias',
      rateLimitPolicy: 'Indexação por nome científico binomial com catálogo local de alta fidelidade',
    },
    {
      id: 'wikipedia-commons',
      name: 'Wikimedia Commons / Wikipedia REST',
      description: 'Fotografias de alta resolução e resumos biológicos enciclopédicos da flora, fauna e fungos.',
      planName: 'Wikimedia Public REST API',
      quotaPerDay: 'Ilimitado (Fair Use ~200 req/s)',
      quotaDailyLimit: 100000,
      quotaWeeklyLimit: 700000,
      quotaUsedToday: quotaCounts['wikipedia-commons'] || 0,
      quotaUsedThisWeek: quotaCounts['wikipedia-commons'] || 0,
      projectedWeeklyUsage: (quotaCounts['wikipedia-commons'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['wikipedia-commons'] || 0) * 7) / 700000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('wikipedia-commons'),
      lastCallTime: getLastTime('wikipedia-commons'),
      cachedEntries: logs.filter((l) => l.provider === 'wikipedia-commons' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['wikipedia-commons'] || 0,
      recommendedTtl: '24 horas (localStorage + CDN)',
      rateLimitPolicy: 'Header User-Agent fidedigno e fallback local imediato em caso de erro',
    },
    {
      id: 'ibama-siscites',
      name: 'IBAMA (SisCITES & Dados Abertos)',
      description: 'Licenças e controle de espécies protegidas da fauna e flora silvestre brasileira (Convenção CITES / MMA).',
      planName: 'Dados.gov.br Open API',
      quotaPerDay: 'Ilimitado (Serviço Público)',
      quotaDailyLimit: 20000,
      quotaWeeklyLimit: 140000,
      quotaUsedToday: quotaCounts['ibama-siscites'] || 0,
      quotaUsedThisWeek: quotaCounts['ibama-siscites'] || 0,
      projectedWeeklyUsage: (quotaCounts['ibama-siscites'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['ibama-siscites'] || 0) * 7) / 140000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('ibama-siscites'),
      lastCallTime: getLastTime('ibama-siscites'),
      cachedEntries: logs.filter((l) => l.provider === 'ibama-siscites' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['ibama-siscites'] || 0,
      recommendedTtl: '24 horas (1 requisição/dia)',
      rateLimitPolicy: 'Chamada única diária agregada com fallback de catálogo embutido',
    },
    {
      id: 'cartodb-tiles',
      name: 'ESRI World Shaded Relief & Physical Atlas',
      description: 'Ladrilhos cartográficos abertos de relevo sombreado, cobertura vegetal natural e topografia sem marcas d’água.',
      planName: 'ArcGIS Open Tile Layer',
      quotaPerDay: '2.500 req/dia (~75k/mês)',
      quotaDailyLimit: 2500,
      quotaWeeklyLimit: 17500,
      quotaUsedToday: quotaCounts['cartodb-tiles'] || 0,
      quotaUsedThisWeek: quotaCounts['cartodb-tiles'] || 0,
      projectedWeeklyUsage: (quotaCounts['cartodb-tiles'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['cartodb-tiles'] || 0) * 7) / 17500) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('cartodb-tiles'),
      lastCallTime: getLastTime('cartodb-tiles'),
      cachedEntries: logs.filter((l) => l.provider === 'cartodb-tiles' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['cartodb-tiles'] || 0,
      recommendedTtl: 'Cache de Disco do Navegador (30 dias)',
      rateLimitPolicy: 'Download sob zoom com renderização vetorial de segurança',
    },
    {
      id: 'satellite-orbital',
      name: 'NASA Earth / ESRI TrueColor HD',
      description: 'Mosaico de satélite orbital com relevo natural da América do Sul e bacias hidrográficas.',
      planName: 'ArcGIS Open Tile Layer',
      quotaPerDay: 'Ilimitado (CDN Cached)',
      quotaDailyLimit: 20000,
      quotaWeeklyLimit: 140000,
      quotaUsedToday: quotaCounts['satellite-orbital'] || 0,
      quotaUsedThisWeek: quotaCounts['satellite-orbital'] || 0,
      projectedWeeklyUsage: (quotaCounts['satellite-orbital'] || 0) * 7,
      usagePercentWeekly: Number(((((quotaCounts['satellite-orbital'] || 0) * 7) / 140000) * 100).toFixed(2)),
      status: 'online',
      avgLatencyMs: getAvgLatency('satellite-orbital'),
      lastCallTime: getLastTime('satellite-orbital'),
      cachedEntries: logs.filter((l) => l.provider === 'satellite-orbital' && l.status === 'cached').length,
      cacheSavingsCalls: cachedSavings['satellite-orbital'] || 0,
      recommendedTtl: 'Cache Persistente de Imagens',
      rateLimitPolicy: 'Ladrilhos estáticos com cache de 7 dias',
    },
    {
      id: 'ibge-geo',
      name: 'IBGE / GeoJSON Malhas Estaduais',
      description: 'Vetorização cartográfica com 27 polígonos estaduais, capitais e coordenadas geodésicas SIRGAS 2000.',
      planName: 'Local-First Static Resource',
      quotaPerDay: 'Ilimitado (0 req externas)',
      quotaDailyLimit: null,
      quotaWeeklyLimit: null,
      quotaUsedToday: quotaCounts['ibge-geo'] || 0,
      quotaUsedThisWeek: quotaCounts['ibge-geo'] || 0,
      projectedWeeklyUsage: 0,
      usagePercentWeekly: 0,
      status: 'online',
      avgLatencyMs: getAvgLatency('ibge-geo'),
      lastCallTime: getLastTime('ibge-geo'),
      cachedEntries: 1,
      cacheSavingsCalls: cachedSavings['ibge-geo'] || 0,
      recommendedTtl: 'Offline Permanente (Zero rede externa)',
      rateLimitPolicy: 'Arquivo empacotado localmente no bundle estático (/br/br.json)',
    },
  ];
}

export function buildWeeklyRecommendations(
  quotaCounts: Record<string, number>
): WeeklyRecommendation[] {
  return [
    {
      providerId: 'open-meteo',
      providerName: 'Open-Meteo (Clima & ECMWF)',
      currentPlan: 'Plano Gratuito Não-Comercial (10.000 req/dia = 70.000/semana)',
      weeklyLimitDisplay: '70.000 req/semana',
      weeklyConsumptionEstimated: Math.max((quotaCounts['open-meteo'] || 0) * 7, 28),
      riskLevel: 'baixo',
      policyInPlace: 'Cache Rígido de 15 Minutos (Lazy Loading)',
      weeklySavingsPct: 96,
      recommendations: [
        'Nunca disparar requisições em intervalos menores que 15 minutos por estado.',
        'Manter execução sob demanda (Lazy Loading): a chamada só ocorre quando o usuário entra na aba Clima.',
        'Economia projetada: mais de 96% de chamadas evitadas graças à checagem de timestamp.',
        'Caso atinja 5.000 req/dia no futuro, considerar chave comercial da Open-Meteo.',
      ],
    },
    {
      providerId: 'gbif-biodiversity',
      providerName: 'GBIF (Biodiversidade & Taxonomia)',
      currentPlan: 'Acesso Científico Aberto Global (Open Access)',
      weeklyLimitDisplay: 'Sem limite fixo (Fair Use de 20 req/s)',
      weeklyConsumptionEstimated: Math.max((quotaCounts['gbif-biodiversity'] || 0) * 7, 14),
      riskLevel: 'baixo',
      policyInPlace: 'Cache de 24 Horas em localStorage',
      weeklySavingsPct: 98,
      recommendations: [
        'Persistir taxonomia de espécimes por 24 horas no localStorage.',
        'Nunca fazer scraping ou varreduras em lote de todos os táxons simultaneamente.',
        'Utilizar endpoint "/species/match" apenas ao clicar no espécime desejado.',
      ],
    },
    {
      providerId: 'inaturalist',
      providerName: 'iNaturalist (Fotografias Científicas do Brasil)',
      currentPlan: 'Acesso Livre para Pesquisa e Educação (Research Grade)',
      weeklyLimitDisplay: 'Fair Use (~60 req/minuto)',
      weeklyConsumptionEstimated: Math.max((quotaCounts['inaturalist'] || 0) * 7, 21),
      riskLevel: 'baixo',
      policyInPlace: 'Fila Concorrente (máx 2 conexões) + Cache de 14 Dias',
      weeklySavingsPct: 99,
      recommendations: [
        'Priorizar observações com fotos no Brasil (place_id=6878) de grau de pesquisa validado.',
        'Garantir cache em memória e localStorage com expiração de 14 dias para fotos de espécimes.',
        'Utilizar throttle mínimo de 250ms e deduplicação de requisições em voo.',
      ],
    },
    {
      providerId: 'jbrj-reflora',
      providerName: 'Flora e Funga do Brasil (JBRJ & Reflora)',
      currentPlan: 'Portal de Dados Abertos Científicos',
      weeklyLimitDisplay: 'Sem cota fixa',
      weeklyConsumptionEstimated: Math.max((quotaCounts['jbrj-reflora'] || 0) * 7, 10),
      riskLevel: 'baixo',
      policyInPlace: 'Correspondência Taxonômica Binomial Estrita',
      weeklySavingsPct: 97,
      recommendations: [
        'Utilizar nomenclatura botânica e micológica binomial oficial.',
        'Associar com vouchers de herbários e coleções do Jardim Botânico do Rio de Janeiro.',
      ],
    },
    {
      providerId: 'ibama-siscites',
      providerName: 'IBAMA / SisCITES (Dados Abertos)',
      currentPlan: 'Portal de Dados Abertos Governamental',
      weeklyLimitDisplay: 'Sem cota fixa (Instabilidade em horários de pico)',
      weeklyConsumptionEstimated: Math.max((quotaCounts['ibama-siscites'] || 0) * 7, 7),
      riskLevel: 'moderado',
      policyInPlace: '1 Requisição Diária com Fallback Local Imediato',
      weeklySavingsPct: 99,
      recommendations: [
        'Limitar a no máximo 1 consulta diária por dispositivo para preservar os servidores governamentais.',
        'Timeout curto (4.5s) com fallback offline para proteger a experiência do usuário se o portal estiver fora do ar.',
      ],
    },
    {
      providerId: 'wikipedia-commons',
      providerName: 'Wikimedia Commons (Fotografias & Textos)',
      currentPlan: 'Wikimedia REST API (Livre)',
      weeklyLimitDisplay: 'Fair Use (~200 req/s)',
      weeklyConsumptionEstimated: Math.max((quotaCounts['wikipedia-commons'] || 0) * 7, 21),
      riskLevel: 'baixo',
      policyInPlace: 'Priorização de Imagem em Alta com Cache e Fallback',
      weeklySavingsPct: 95,
      recommendations: [
        'Requisitar apenas miniaturas e resumos sob demanda com componente BiodiversityImage resiliente.',
        'Manter URLs canônicas da Wikimedia no catálogo base para evitar buscas cegas.',
      ],
    },
    {
      providerId: 'cartodb-tiles',
      providerName: 'CartoDB / OpenStreetMap Tiles',
      currentPlan: 'Plano Gratuito Aberto (75.000 req/mês = ~17.500/semana)',
      weeklyLimitDisplay: '17.500 req/semana',
      weeklyConsumptionEstimated: Math.max((quotaCounts['cartodb-tiles'] || 0) * 7, 35),
      riskLevel: 'baixo',
      policyInPlace: 'Cache Nativo HTTP e Camada Vetorial',
      weeklySavingsPct: 90,
      recommendations: [
        'Aproveitar o cache HTTP do navegador para evitar recarregamento de quadrículas já visualizadas.',
        'Priorizar renderização vetorial no modo padrão do mapa.',
      ],
    },
  ];
}
